M48
; DRILL file {KiCad 7.0.7} date Thu Oct 19 13:35:08 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-19T13:35:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0492
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X1.137Y-1.1386
X1.137Y-1.8386
T2
X1.1Y-0.9
X1.1Y-5.15
X3.4Y-0.9
X3.4Y-5.15
T0
M30
