M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Wed 18 Oct 2023 03:00:27 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-18T15:00:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0492
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X1.137Y-1.1386
X1.137Y-1.8386
T2
X1.1Y-0.9
X1.1Y-5.15
X3.4Y-0.9
X3.4Y-5.15
T0
M30
